FROM ubuntu:22.04

LABEL maintainer="wagnerdocri@gmail.com"

# Let the container know that there is no tty
ENV DEBIAN_FRONTEND noninteractive


RUN apt-get update -y

#dev helper packages
RUN apt-get install -y iputils-ping curl wget vim nmap

RUN apt-get install -y software-properties-common curl gnupg2 wget -y

RUN add-apt-repository -y ppa:ondrej/php

RUN apt-get install -y php7.4 php7.4-fpm -y

RUN apt-get install -y php7.4-cli php7.4-mbstring php7.4-xml php7.4-gd php7.4-mysql php7.4-curl

#Installing php modules
RUN apt-get install -y php7.4-soap php7.4-xml php7.4-pdo php7.4-ldap php7.4-intl php7.4-fpm php7.4-cli
RUN apt-get install -y graphviz aspell ghostscript clamav php7.4-pspell
RUN apt-get install -y php7.4-sqlite3 php7.4-mysqli php7.4-pgsql php7.4-pdo-pgsql php7.4-mysql php7.4-pdo-mysql
RUN apt-get install -y php7.4-opcache php7.4-curl php7.4-gd php7.4-zip php7.4-mbstring

#Copy configuration files
COPY php.ini-development /etc/php/7.4/fpm/php.ini
COPY php-fpm-dev.conf /etc/php/7.4/fpm/php-fpm.conf
#www-dev.conf is the pool inside /usr/local/php-fpm.d/*.conf mounted dir at runs container

CMD ["php-fpm7.4", "-F"]

