FROM ubuntu:24.10

# Install Apache and additional tools
RUN apt-get update && \
    apt-get install -y \
    apache2 \
    iputils-ping \
    curl \
    wget \
    vim \
    nmap \
    git \    
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    libcurl4-openssl-dev \
    libzip4 \
    libzip-dev \
    libsodium-dev

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Enable Apache modules
RUN a2enmod proxy_fcgi

# Configure Apache VirtualHost
COPY 000-default-dev.conf /etc/apache2/sites-available/000-default.conf
COPY ./90-xdebug.ini "${PHP_INI_DIR}/conf.d"  

RUN chgrp www-data -R /var/www/html
RUN chmod 750 -R /var/www/html
RUN chmod g+s /var/www/html

#The last command makes all files/folders created within the directory to automatically
#take on the group ownership of the parent folder,
#that is your web server.
#The s flags is a special mode that represents the setuid/setgid.
#In simple words, new files and directories created by the web server
#will have the same group ownership of html/ folder,
#which we set to www-data with the second command.
#https://www.internalpointers.com/post/right-folder-permission-website

# RUN useradd -G www-data,root -u $uid -d /home/$user $user
# RUN mkdir -p /home/$user/.composer && \
#     chown -R $user:$user /home/$user

EXPOSE 80

USER ${user}

CMD ["apachectl", "-D", "FOREGROUND"]
