FROM ubuntu:24.10

LABEL maintainer="wagnerdocri@gmail.com"

# Let the container know that there is no tty
ENV DEBIAN_FRONTEND noninteractive


RUN apt-get update -y

#dev helper packages
RUN apt-get install -y iputils-ping curl wget vim nmap

#Installing PHP 8.3.6 (cli) (built: Apr 15 2024 19:21:47) (NTS)
#Copyright (c) The PHP Group
#Zend Engine v4.3.6, Copyright (c) Zend Technologies
#    with Zend OPcache v8.3.6, Copyright (c), by Zend Technologies
RUN apt-get install -y php

#Installing php modules
RUN apt-get install -y php-soap php-xml php-pdo php-ldap php-intl php-fpm php-cli
RUN apt-get install -y graphviz aspell ghostscript clamav php-pspell
RUN apt-get install -y php-sqlite3 php-mysqli php-pgsql php-pdo-pgsql php-mysql php-pdo-mysql
RUN apt-get install -y php-opcache php-curl php-gd php-zip php-mbstring

#Copy configuration files
COPY php.ini-development /etc/php/8.3/fpm/php.ini
COPY php-fpm-dev.conf /etc/php/8.3/fpm/php-fpm.conf
#www-dev.conf is the pool inside /usr/local/php-fpm.d/*.conf mounted dir at runs container

EXPOSE 9008

CMD ["php-fpm8.3", "-F"]

